#!/bin/bash

set -e

RED='\e[1;31m'
RESET_COLOR='\033[0m'

if ! command -v virt-install &> /dev/null; then
	echo -e "$RED" "You must install the virt-install package to continue. Aborting.""$RESET_COLOR"
	exit 1
fi

if [[ ! -d "/usr/share/OVMF" ]]; then
	echo -e "$RED" "You must install the ovmf or the edk2-ovmf package to continue. Aborting.""$RESET_COLOR"
	exit 1
fi

if [[ "$EUID" -eq "0" ]]; then
	echo -e "$RED" "Run this script as non root to continue. Aborting.""$RESET_COLOR"
	exit 1
fi

help() {
        echo -e "\e[1;32mVIRSH VM creation

\e[0;33mUSAGE
        \e[1;35mBase command syntax\e[0;33m: \e[1;36m./virsh-vm-install \e[1;35m-n\e[0;33m/\e[1;35m--name\e[0;33m \e[1;36mNAME \e[1;35m-m\e[0;33m/\e[1;35m--memory\e[0;33m\e[0;33m \e[1;36mMEMORY \e[1;35m-v\e[0;33m/\e[1;35m--vcpus\e[0;33m \e[1;36mVCPUS \e[1;35m-c\e[0;33m/\e[1;35m--cdrom\e[0;33m \e[1;36mCDROM \e[1;35m-d\e[0;33m/\e[1;35m--disk-size\e[0;33m \e[1;36mDISK-SIZE
        \e[1;35mDisplay usage\e[0;33m: \e[1;36m./virsh-vm-install \e[1;35m-h\e[0;33m/\e[1;35m--help

\e[0;33mEXPLAINATION
                Arguments must be used with this script:
                \e[1;35m-h\e[0;33m|\e[1;35m--help\e[0;33m: Display help
                \e[1;35m-n\e[0;33m|\e[1;35m--name\e[0;33m: Set the domain name, example \e[1;36mtest
                \e[1;35m-m\e[0;33m|\e[1;35m--memory\e[0;33m: Set the RAM size (in Mb), example \e[1;36m8192
                \e[1;35m-v\e[0;33m|\e[1;35m--vcpus\e[0;33m: Set the number of vcpus, example \e[1;36m2
                \e[1;35m-c\e[0;33m|\e[1;35m--cdrom\e[0;33m: Select the path of the ISO to use to install the VM, example \e[1;36m~/ISO/test.iso
                \e[1;35m-d\e[0;33m|\e[1;35m--disk-size\e[0;33m: Set the disk size (in Gb), example \e[1;36m20

		\e[0;33mOptional arguments:
                \e[1;35m-t\e[0;33m|\e[1;35m--tpm\e[0;33m: Add an emulated 2.0 TPM device (required for Windows 11)
                \e[1;35m-p\e[0;33m|\e[1;35m--paravirtualization\e[0;33m: Use the paravirtualization instead of the full virtualization (VirtIO drivers)
                \e[1;35m-u\e[0;33m|\e[1;35m--uefi\e[0;33m: Enable UEFI without Secure Boot
                \e[1;35m-s\e[0;33m|\e[1;35m--secure-boot\e[0;33m: Enable UEFI with Secure Boot
                \e[1;35m-f\e[0;33m|\e[1;35m--filesystem\e[0;33m: Share a local folder into the VM

\e[0;33mEXAMPLES
        To create a Fedora VM with 20Gb of disk, 4Go of RAM and 2 vCPUs with short arguments:
        \e[1;36m./virsh-vm-install \e[1;35m-n \e[1;36mFedora \e[1;35m-m \e[1;36m4096 \e[1;35m-v \e[1;36m2 \e[1;35m-c \e[1;36m~/ISO/fedora.iso \e[1;35m-d \e[1;36m20 \e[0;33m
        \e[0;33mTo create a Fedora VM with 20Gb of disk, 4Go of RAM and 2 vCPUs with shared local folder:
        \e[1;36m./virsh-vm-install \e[1;35m-n \e[1;36mFedora \e[1;35m-m \e[1;36m4096 \e[1;35m-v \e[1;36m2 \e[1;35m-c \e[1;36m~/ISO/fedora.iso \e[1;35m-d \e[1;36m20 \e[1;35m-f \e[1;36m/home,guest_shared_name \e[0;33m
        \e[0;33mTo create a Fedora VM with 20Gb of disk, 4Go of RAM and 2 vCPUs with paravirtualization:
        \e[1;36m./virsh-vm-install \e[1;35m-n \e[1;36mFedora \e[1;35m-m \e[1;36m4096 \e[1;35m-v \e[1;36m2 \e[1;35m-c \e[1;36m~/ISO/fedora.iso \e[1;35m-d \e[1;36m20 \e[1;35m-p \e[0;33m
        \e[0;33mTo create a Fedora VM with 20Gb of disk, 4Go of RAM and 2 vCPUs with UEFI without Secure Boot:
        \e[1;36m./virsh-vm-install \e[1;35m-n \e[1;36mFedora \e[1;35m-m \e[1;36m4096 \e[1;35m-v \e[1;36m2 \e[1;35m-c \e[1;36m~/ISO/fedora.iso \e[1;35m-d \e[1;36m20 \e[1;35m-u \e[0;33m
        \e[0;33mTo create a Fedora VM with 20Gb of disk, 4Go of RAM and 2 vCPUs with UEFI and Secure Boot:
        \e[1;36m./virsh-vm-install \e[1;35m-n \e[1;36mFedora \e[1;35m-m \e[1;36m4096 \e[1;35m-v \e[1;36m2 \e[1;35m-c \e[1;36m~/ISO/fedora.iso \e[1;35m-d \e[1;36m20 \e[1;35m-s \e[0;33m
        \e[0;33mTo create a Fedora VM with 20Gb of disk, 4Go of RAM and 2 vCPUs with UEFI and Secure Boot and emulated TPM device:
        \e[1;36m./virsh-vm-install \e[1;35m-n \e[1;36mFedora \e[1;35m-m \e[1;36m4096 \e[1;35m-v \e[1;36m2 \e[1;35m-c \e[1;36m~/ISO/fedora.iso \e[1;35m-d \e[1;36m20 \e[1;35m-s \e[0;33m\e[1;35m-t \e[0;33m

        To create a Fedora VM with 20Gb of disk, 4Go of RAM and 2 vCPUs with long arguments:
        \e[1;36m./virsh-vm-install \e[1;35m--name \e[1;36mFedora \e[1;35m--memory \e[1;36m4096 \e[1;35m--vcpus \e[1;36m2 \e[1;35m--cdrom \e[1;36m~/ISO/fedora.iso \e[1;35m--disk \e[1;36m20 \e[0;33m
        \e[0;33mTo create a Fedora VM with 20Gb of disk, 4Go of RAM and 2 vCPUs with shared local folder:
        \e[1;36m./virsh-vm-install \e[1;35m--name \e[1;36mFedora \e[1;35m--memory \e[1;36m4096 \e[1;35m--vcpus \e[1;36m2 \e[1;35m--cdrom \e[1;36m~/ISO/fedora.iso \e[1;35m--disk \e[1;36m20 \e[1;35m--filesystem \e[1;36m/home,guest_shared_name \e[0;33m
        \e[0;33mTo create a Fedora VM with 20Gb of disk, 4Go of RAM and 2 vCPUs with paravirtualization:
        \e[1;36m./virsh-vm-install \e[1;35m--name \e[1;36mFedora \e[1;35m--memory \e[1;36m4096 \e[1;35m--vcpus \e[1;36m2 \e[1;35m--cdrom \e[1;36m~/ISO/fedora.iso \e[1;35m--disk \e[1;36m20 \e[1;35m--paravirtualization \e[0;33m
        \e[0;33mTo create a Fedora VM with 20Gb of disk, 4Go of RAM and 2 vCPUs with UEFI without Secure Boot:
        \e[1;36m./virsh-vm-install \e[1;35m--name \e[1;36mFedora \e[1;35m--memory \e[1;36m4096 \e[1;35m--vcpus \e[1;36m2 \e[1;35m--cdrom \e[1;36m~/ISO/fedora.iso \e[1;35m--disk \e[1;36m20 \e[1;35m--uefi \e[0;33m
        \e[0;33mTo create a Fedora VM with 20Gb of disk, 4Go of RAM and 2 vCPUs with UEFI and Secure Boot:
        \e[1;36m./virsh-vm-install \e[1;35m--name \e[1;36mFedora \e[1;35m--memory \e[1;36m4096 \e[1;35m--vcpus \e[1;36m2 \e[1;35m--cdrom \e[1;36m~/ISO/fedora.iso \e[1;35m--disk \e[1;36m20 \e[1;35m--secure-boot \e[0;33m
        \e[0;33mTo create a Fedora VM with 20Gb of disk, 4Go of RAM and 2 vCPUs with UEFI and Secure Boot and emulated TPM device:
        \e[1;36m./virsh-vm-install \e[1;35m--name \e[1;36mFedora \e[1;35m--memory \e[1;36m4096 \e[1;35m--vcpus \e[1;36m2 \e[1;35m--cdrom \e[1;36m~/ISO/fedora.iso \e[1;35m--disk \e[1;36m20 \e[1;35m--secure-boot\e[0;33m \e[1;35m--tpm \e[0;33m
"
exit 0
}

ARGS=$(getopt -o n:m:v:c:d:f:tpush -l name:,memory:,vcpus:,cdrom:,disk-size:,filesystem:,tpm,paravirtualization,uefi,secure-boot,help -- "$@")
eval set -- "$ARGS"
while true
do
        case "$1" in
                -n|--name) NAME=$2; shift 2; ;;
                -m|--memory) MEMORY=$2; shift 2; ;;
                -v|--vcpus) VCPUS=$2; shift 2; ;;
                -c|--cdrom) CDROM=$2; shift 2; ;;
                -d|--disk-size) DISK=$2; shift 2; ;;
		-f|--filesystem) FILESYSTEM=$2; shift 2; ;;
		-t|--tpm) TPM=on; shift; ;;
		-p|--paravirtualization) VIRTIO=on; shift; ;;
		-u|--uefi) UEFI=on; shift; ;;
		-s|--secure-boot) SECUREBOOT=on; shift; ;;
                -h|--help) help; ;;
                --) shift; break; ;;
                 *) echo "Internal error, unhandled option: $1"; exit 1; ;;
        esac
done

if [[ -z "${NAME}" ]] || [[ -z "${MEMORY}" ]] || [[ -z "${VCPUS}" ]] || [[ -z "${CDROM}" ]] || [[ -z "${DISK}" ]]; then
	"$0" -h
	exit 1
fi

if [[ "${MEMORY}" -lt "512" ]]; then
	echo "The size of RAM is too weak (actual value: "${MEMORY}"). Please increase the value (minimal 512 Mib required). Aborting."
	exit 1
fi

if [[ -z $UEFI ]] && [[ -z $SECUREBOOT ]]; then
	BOOT_OPTIONS="uefi=off"
fi

if [[ "$UEFI" = "on" ]] && [[ -z $SECUREBOOT ]]; then
	BOOT_OPTIONS="uefi=on,firmware.feature0.name=secure-boot,firmware.feature0.enabled=no,firmware.feature1.name=enrolled-keys,firmware.feature1.enabled=no"
fi

if [[ -z "$UEFI" ]] && [[ "$SECUREBOOT" = "on" ]] || [[ "$UEFI" = "on" ]] && [[ "$SECUREBOOT" = "on" ]]; then
	BOOT_OPTIONS="uefi=on,firmware.feature0.name=secure-boot,firmware.feature0.enabled=yes,firmware.feature1.name=enrolled-keys,firmware.feature1.enabled=yes"
fi

if [[ ! -z "$FILESYSTEM" ]]; then
	FILESYSTEM="--filesystem "${FILESYSTEM}",driver.type=virtiofs,type=mount,accessmode=passthrough --memorybacking=source.type=memfd,access.mode=shared"
fi

if [[ "$TPM" = "on" ]]; then
	TPM="--tpm model=tpm-crb"
else
	TPM="--tpm none"
fi

if [[ "$VIRTIO" = "on" ]]; then
	DISK_BUS="target.bus=virtio"
	NETWORK_CARD_MODEL="model.type=virtio"
	GL="gl=on"
	VIDEO_PARAMS="virtio,accel3d=yes,vram=8192"
	MEMBALLOON="virtio"
else
	DISK_BUS="target.bus=sata"
	NETWORK_CARD_MODEL="model.type=e1000e"
	GL="gl=off"
	VIDEO_PARAMS="qxl,accel3d=no,vram=8192,vram64=8192,vgamem=8192"
	MEMBALLOON="none"
fi

virt-install \
	--connect qemu:///session \
	--hvm \
	--virt-type kvm \
	--machine q35 \
	--cpu host-model \
	--graphics spice,listen=none,${GL} \
	--video ${VIDEO_PARAMS} \
	--memballoon ${MEMBALLOON} \
	--clock offset=localtime \
	--console none \
	--noautoconsole \
	--osinfo detect=off,require=off \
	--os-variant detect=off,require=off \
	--input none \
	--controller type=usb,model=qemu-xhci \
	--sound model=ich9 \
	--check all=off \
	--name "${NAME}" \
	--memory "${MEMORY}" \
	--vcpus "${VCPUS}" \
	--cdrom "${CDROM}" \
	--network bridge=virbr0,"${NETWORK_CARD_MODEL}" \
	--disk size="${DISK}","${DISK_BUS}" \
	--boot hd,cdrom,bootmenu.enable=on,${BOOT_OPTIONS} \
	${FILESYSTEM} \
	${TPM}
